export const CAMERA_PERMISSION_REQUESTED = 'CAMERA_PERMISSION_REQUESTED';
export const CAMERA_PERMISSION_SUCCESS = 'CAMERA_PERMISSION_SUCCESS';
export const CAMERA_PERMISSION_FAILED = 'CAMERA_PERMISSION_FAILED';
export const CAMERA_CAPTURE_REQUESTED = 'CAMERA_CAPTURE_REQUESTED';
export const CAMERA_CAPTURE_SUCCESS = 'CAMERA_CAPTURE_SUCCESS';
export const CAMERA_CAPTURE_FAILED = 'CAMERA_CAPTURE_FAILED';
