export const CAMERA_PERMISSION_REQUESTED = 'CAMERA_PERMISSION_REQUESTED';
export const CAMERA_PERMISSION_SUCCESS = 'CAMERA_PERMISSION_REQUESTED';
export const CAMERA_PERMISSION_FAILED = 'CAMERA_PERMISSION_REQUESTED';
