export const ADD_PHOTOS_REQUESTED = 'ADD_PHOTOS_REQUESTED';
export const ADD_PHOTOS_SUCCESS = 'ADD_PHOTOS_SUCCESS';
export const ADD_PHOTOS_FAILED = 'ADD_PHOTOS_FAILED';
export const CLEAR_PHOTOS = 'CLEAR_PHOTOS';
