export const GET_RESULT_REQUESTED = 'GET_RESULT_REQUESTED';
export const GET_RESULT_SUCCESS = 'GET_RESULT_SUCCESS';
export const GET_RESULT_FAILED = 'GET_RESULT_FAILED ';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
